//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132986.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BookedRoom
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public BookedRoom()
        {
            this.ServiceUsages = new HashSet<ServiceUsage>();
            this.Invoices = new HashSet<Invoice>();
        }
    
        public int ID { get; set; }
        public int RoomID { get; set; }
        public bool CheckinType { get; set; }
        public System.DateTime CheckinDay { get; set; }
        public System.DateTime CheckoutDay { get; set; }
        public Nullable<int> UserID { get; set; }
        public string CustomerID { get; set; }
        public System.DateTime BookDate { get; set; }
        public bool PaymentStatus { get; set; }
        public bool CheckinStatus { get; set; }
        public string BookingStatus { get; set; }
        public Nullable<System.DateTime> CancelDay { get; set; }

        public virtual Customer Customer { get; set; }
        public virtual Room Room { get; set; }
        public virtual UserInfo UserInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ServiceUsage> ServiceUsages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Invoice> Invoices { get; set; }
    }
}
