//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132986.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Invoice
    {
        public int ID { get; set; }
        public int BookedRoomID { get; set; }
        public decimal TotalPrice { get; set; }
        public int TotalBookedDay { get; set; }
        public Nullable<int> PaymentMethod { get; set; }
    
        public virtual BookedRoom BookedRoom { get; set; }
    }
}
