//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132986.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Room
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Room()
        {
            this.RoomImageGalleries = new HashSet<RoomImageGallery>();
            this.BookedRooms = new HashSet<BookedRoom>();
        }
    
        public int ID { get; set; }
        [Required(ErrorMessage = "This field is requried")]

        public string RoomName { get; set; }

        [Required(ErrorMessage = "This field is requried")]

        public Nullable<int> RoomTypeID { get; set; }
        [Required(ErrorMessage = "This field is requried")]

        public bool RoomStatus { get; set; }
        [Required(ErrorMessage = "This field is requried")]

        public string RoomDescription { get; set; }
        [Required(ErrorMessage = "This field is requried")]

        public string RoomFeature { get; set; }

        [Required(ErrorMessage = "This field is requried")]

        public virtual RoomType RoomType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RoomImageGallery> RoomImageGalleries { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<BookedRoom> BookedRooms { get; set; }
    }
}
