//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132986.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceUsage
    {
        public int ID { get; set; }
        public int BookedRoomID { get; set; }
        public int ServiceID { get; set; }
    
        public virtual BookedRoom BookedRoom { get; set; }
        public virtual HotelService HotelService { get; set; }
    }
}
