//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_63132986.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SliderBannerImage
    {
        public int ID { get; set; }
        public string BannerImage { get; set; }
        public int ImageOrder { get; set; }
        public string Link { get; set; }
        public string Title { get; set; }
        public string Content { get; set; }
    }
}
